# Generated by Django 4.0.6 on 2023-03-21 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email format')])),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='sos_photos/')),
            ],
        ),
    ]
