# Generated by Django 4.0.6 on 2023-03-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velifem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=3)),
                ('contact_number', models.CharField(max_length=10)),
                ('animal_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Hamster', 'Hamster'), ('Fish', 'Fish')], max_length=20)),
                ('breed', models.CharField(max_length=50)),
                ('annual_income', models.CharField(choices=[('0 - 300,000', '0 - 300,000'), ('300,000 - 500,000', '300,000 - 500,000'), ('500,000 - 700,000', '500,000 - 700,000'), ('700,000 - 900,000', '700,000 - 900,000'), ('900,000 - 1,100,000', '900,000 - 1,100,000'), ('> 1,100,000', '> 1,100,000')], max_length=30)),
                ('permanent_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SOSRequest',
            new_name='SOS',
        ),
    ]
