# Generated by Django 4.0.6 on 2023-03-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velifem', '0004_login_registration_alter_adoption_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='breed',
            field=models.CharField(choices=[('Golden Retreiver', 'Golden Retreiver'), ('Labrador', 'Labrador'), ('Shih Tzu', 'Shih Tzu'), ('Indian Periah', 'Indian Periah'), ('Siberian Husky', 'Siberian Husky'), ('British Shorthair', 'British Shorthair'), ('Persian Cat', 'Persian Cat'), ('Maine Coon', 'Maine Coon'), ('Scotish Fold', 'Scotish Fold'), ('Siamese Cat', 'Siamese Cat'), ('Syrian Hamster', 'Syrian Hamster'), ('Chinese Hamster', 'Chinese Hamster'), ('Budgerigar', 'Budgerigar'), ('Cockatiel', 'Cockatiel'), ('Black Moor', 'Black Moor'), ('Golden Fish', 'Golden Fish')], max_length=50),
        ),
    ]
