# Generated by Django 4.0.6 on 2023-03-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velifem', '0006_remove_donation_amount_remove_donation_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
