# Generated by Django 4.0.6 on 2023-03-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velifem', '0007_donation_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='adoption',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='adoption',
            name='breed',
        ),
    ]
