# Generated by Django 4.0.6 on 2023-03-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velifem', '0008_remove_adoption_animal_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
